package cas

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// ListUserCertificateDetail invokes the cas.ListUserCertificateDetail API synchronously
// api document: https://help.aliyun.com/api/cas/ListUserCertificateDetail.html
func (client *Client) ListUserCertificateDetail(request *ListUserCertificateDetailRequest) (response *ListUserCertificateDetailResponse, err error) {
	response = CreateListUserCertificateDetailResponse()
	err = client.DoAction(request, response)
	return
}

// ListUserCertificateDetailWithChan invokes the cas.ListUserCertificateDetail API asynchronously
// api document: https://help.aliyun.com/api/cas/ListUserCertificateDetail.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) ListUserCertificateDetailWithChan(request *ListUserCertificateDetailRequest) (<-chan *ListUserCertificateDetailResponse, <-chan error) {
	responseChan := make(chan *ListUserCertificateDetailResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.ListUserCertificateDetail(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// ListUserCertificateDetailWithCallback invokes the cas.ListUserCertificateDetail API asynchronously
// api document: https://help.aliyun.com/api/cas/ListUserCertificateDetail.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) ListUserCertificateDetailWithCallback(request *ListUserCertificateDetailRequest, callback func(response *ListUserCertificateDetailResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *ListUserCertificateDetailResponse
		var err error
		defer close(result)
		response, err = client.ListUserCertificateDetail(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// ListUserCertificateDetailRequest is the request struct for api ListUserCertificateDetail
type ListUserCertificateDetailRequest struct {
	*requests.RpcRequest
	ShowSize    requests.Integer `position:"Query" name:"ShowSize"`
	CurrentPage requests.Integer `position:"Query" name:"CurrentPage"`
	SourceIp    string           `position:"Query" name:"SourceIp"`
	Lang        string           `position:"Query" name:"Lang"`
}

// ListUserCertificateDetailResponse is the response struct for api ListUserCertificateDetail
type ListUserCertificateDetailResponse struct {
	*responses.BaseResponse
	RequestId       string        `json:"RequestId" xml:"RequestId"`
	TotalCount      int           `json:"TotalCount" xml:"TotalCount"`
	ShowSize        int           `json:"ShowSize" xml:"ShowSize"`
	CurrentPage     int           `json:"CurrentPage" xml:"CurrentPage"`
	CertificateList []Certificate `json:"CertificateList" xml:"CertificateList"`
}

// CreateListUserCertificateDetailRequest creates a request to invoke ListUserCertificateDetail API
func CreateListUserCertificateDetailRequest() (request *ListUserCertificateDetailRequest) {
	request = &ListUserCertificateDetailRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("cas", "2018-07-13", "ListUserCertificateDetail", "cas", "openAPI")
	request.Method = requests.POST
	return
}

// CreateListUserCertificateDetailResponse creates a response to parse from ListUserCertificateDetail response
func CreateListUserCertificateDetailResponse() (response *ListUserCertificateDetailResponse) {
	response = &ListUserCertificateDetailResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}